/* This file was automatically generated by CasADi 3.6.5+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int f_alloc_mem(void);
extern "C" int f_init_mem(int mem);
extern "C" void f_free_mem(int mem);
extern "C" int f_checkout(void);
extern "C" void f_release(int mem);
extern "C" void f_incref(void);
extern "C" void f_decref(void);
extern "C" casadi_int f_n_in(void);
extern "C" casadi_int f_n_out(void);
extern "C" casadi_real f_default_in(casadi_int i);
extern "C" const char* f_name_in(casadi_int i);
extern "C" const char* f_name_out(casadi_int i);
extern "C" const casadi_int* f_sparsity_in(casadi_int i);
extern "C" const casadi_int* f_sparsity_out(casadi_int i);
extern "C" int f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int f_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define f_SZ_ARG 2
#define f_SZ_RES 1
#define f_SZ_IW 0
#define f_SZ_W 6
extern "C" int solver(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int solver_alloc_mem(void);
extern "C" int solver_init_mem(int mem);
extern "C" void solver_free_mem(int mem);
extern "C" int solver_checkout(void);
extern "C" void solver_release(int mem);
extern "C" void solver_incref(void);
extern "C" void solver_decref(void);
extern "C" casadi_int solver_n_in(void);
extern "C" casadi_int solver_n_out(void);
extern "C" casadi_real solver_default_in(casadi_int i);
extern "C" const char* solver_name_in(casadi_int i);
extern "C" const char* solver_name_out(casadi_int i);
extern "C" const casadi_int* solver_sparsity_in(casadi_int i);
extern "C" const casadi_int* solver_sparsity_out(casadi_int i);
extern "C" int solver_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int solver_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define solver_SZ_ARG 12
#define solver_SZ_RES 10
#define solver_SZ_IW 0
#define solver_SZ_W 5306
